name: Publish to npm

on:
  push:
    branches:
      - main  # or any branch you want to trigger the publish
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # or any version you prefer
          registry-url: 'https://registry.npmjs.org'
      # - run: npm ci
      # - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
